server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
pagehelper:
  helper-dialect: mysql
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug
mybatis:
<<<<<<< HEAD
  type-handlers-package: com.cskaoyan.mall.handler



=======
  type-handlers-package: com.cskaoyan.mall.handler
>>>>>>> f1ddb115bee9c58349e44ab0b66e9278d63014cf
